In [1]:
import re
import datetime
from pychattr.channel_attribution import MarkovModel
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report

In [ ]:
df = pd.read_csv('/home/mam_jupyter/jupyter_dir/artefact/attribution/tp_analysis/data/tp_analysis_base.csv',sep = '\t',header = None)
id_mapping = pd.read_csv('/home/mam_jupyter/jupyter_dir/artefact/attribution/tp_analysis/data/id_mapping.csv')

In [5]:
id_mapping.head()

,touchpoint_id,touchpoint_name,touchpoint_level,is_inbound,touchpoint_owner,touchpoint_channel,data_source,level_1,level_2,level_3,level_4,level_1_name,level_2_name,level_3_name,level_4_name
0,003001003008_tp,展厅首页 - 优选网点-查看更多,4,1,1,1,app,003000000000_tp,003001000000_tp,003001003000_tp,003001003008_tp,线上展厅访问,APP展厅访问,展厅首页核心按钮点击,展厅首页 - 优选网点-查看更多
1,003001003009_tp,展厅首页 - 优选网点-电话,4,1,1,1,app,003000000000_tp,003001000000_tp,003001003000_tp,003001003009_tp,线上展厅访问,APP展厅访问,展厅首页核心按钮点击,展厅首页 - 优选网点-电话
2,003001003010_tp,展厅首页 - 金融服务,4,1,1,1,app,003000000000_tp,003001000000_tp,003001003000_tp,003001003010_tp,线上展厅访问,APP展厅访问,展厅首页核心按钮点击,展厅首页 - 金融服务
3,003001003011_tp,展厅首页 - 订购入口,4,1,1,1,app,003000000000_tp,003001000000_tp,003001003000_tp,003001003011_tp,线上展厅访问,APP展厅访问,展厅首页核心按钮点击,展厅首页 - 订购入口
4,003001003012_tp,展厅首页 - 最近活动,4,1,1,1,app,003000000000_tp,003001000000_tp,003001003000_tp,003001003012_tp,线上展厅访问,APP展厅访问,展厅首页核心按钮点击,展厅首页 - 最近活动

In [6]:
df = pd.read_csv('/home/mam_jupyter/jupyter_dir/artefact/attribution/tp_analysis/tp_analysis_base.csv',sep = '\t',header = None)

In [7]:
df.head()

,0,1,2,3,4,5,6,7
0,13000000133,002011005007_tp,2020-10-28 11:16:45,1,NaN,NaN,NaN,NaN
1,13000001122,004000000000_tp,2020-09-11 11:08:51,17,2020-09-10 16:42:19,009002007000_tp,17.0,-1.0
2,13000009999,009002001000_tp,2020-06-17 21:51:59,25,2020-06-12 22:11:50,009002001000_tp,25.0,-5.0
3,13001035033,002009001003_tp,2020-06-24 11:20:03,24,2020-06-23 08:42:48,002009001003_tp,24.0,-1.0
4,13001055006,009002001000_tp,2020-11-02 09:38:09,10,2020-10-28 10:46:06,002011005007_tp,10.0,-5.0

In [8]:
df = df.rename(columns = {0:'mobile',1:'touchpoint_id',2:'action_time'})

In [9]:
df = df[['mobile','action_time','touchpoint_id']]
df.head()

        mobile          action_time    touchpoint_id
0  13000000133  2020-10-28 11:16:45  002011005007_tp
1  13000001122  2020-09-11 11:08:51  004000000000_tp
2  13000009999  2020-06-17 21:51:59  009002001000_tp
3  13001035033  2020-06-24 11:20:03  002009001003_tp
4  13001055006  2020-11-02 09:38:09  009002001000_tp

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44711018 entries, 0 to 44711017
Data columns (total 3 columns):
 #   Column         Dtype
---  ------         -----
 0   mobile         int64
 1   action_time    object
 2   touchpoint_id  object
dtypes: int64(1), object(2)
memory usage: 1023.4+ MB

In [11]:
def preprocess(df):
    df.dropna(inplace = True)
    df['mobile'] = df['mobile'].astype('string')
    ##filter the uncleaned mobile
    df = df[df.mobile.str.contains('^1\d{10}$')]
    ##phone number of dealer to remove
    mobile_to_remove = pd.read_csv('mobile_to_remove.csv').drop(columns =[ 'Unnamed: 0'])
    mobile_to_remove_list = mobile_to_remove.mobile.unique()
    df = df[~df.mobile.isin(mobile_to_remove_list)]
    ##删除无效节点：005000000000_tp，004000000000_tp
    df = df[~df.touchpoint_id.isin(['005000000000_tp','004000000000_tp'])]
    return df

In [12]:
df = preprocess(df)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 39002112 entries, 0 to 44711017
Data columns (total 3 columns):
 #   Column         Dtype
---  ------         -----
 0   mobile         string
 1   action_time    object
 2   touchpoint_id  object
dtypes: object(2), string(1)
memory usage: 1.2+ GB

In [14]:
# ##use toucpoint_name
# df = df.merge(id_mapping[['touchpoint_id','touchpoint_name']], on = 'touchpoint_id')
# df = df[['mobile','action_time','touchpoint_name']]

In [15]:
# link consumer journey
df = df.sort_values(['mobile', 'action_time'],ascending=[False, True])
df_paths = df.groupby('mobile')['touchpoint_id'].aggregate(lambda x: x.tolist()).reset_index()

In [16]:
df_paths.head()

        mobile                                      touchpoint_id
0  13000000003  [008002007000_tp, 009002002000_tp, 00201100500...
1  13000000004                 [002011002000_tp, 002011002000_tp]
2  13000000005  [008002007000_tp, 009002004000_tp, 00201100500...
3  13000000008  [002011005007_tp, 002011005007_tp, 00201100400...
4  13000000012                                  [002011005007_tp]

In [17]:
def if_has_endpoint(touchpoint_id,list1):
    if touchpoint_id in list1:
        return 1
    else:
        return 0

def exclude_endpoint(touchpoint_id,list1):
    list1 = list1[:list1.index(touchpoint_id)]
    return list1

In [18]:
df_paths['if_order'] = df_paths['touchpoint_id'].apply(lambda x:if_has_endpoint('011000000000_tp',x))

In [19]:
df_paths.if_order.value_counts()

0    3151232
1     189562
Name: if_order, dtype: int64

In [20]:
df_paths.loc[df_paths.if_order == 1,'touchpoint_id'] = df_paths.loc[df_paths.if_order == 1,'touchpoint_id'].apply(lambda x:exclude_endpoint('011000000000_tp',x))
df_paths = df_paths[df_paths['touchpoint_id'].str.len() > 0]

In [21]:
df_paths.if_order.value_counts()

0    3151232
1     141363
Name: if_order, dtype: int64

In [22]:
df_paths.head()

        mobile                                      touchpoint_id  if_order
0  13000000003  [008002007000_tp, 009002002000_tp, 00201100500...         0
1  13000000004                 [002011002000_tp, 002011002000_tp]         0
2  13000000005  [008002007000_tp, 009002004000_tp, 00201100500...         0
3  13000000008  [002011005007_tp, 002011005007_tp, 00201100400...         0
4  13000000012                                  [002011005007_tp]         0

In [23]:
df_paths['path'] = df_paths['touchpoint_id'].apply(lambda x: ",".join(x))

In [24]:
df_paths = df_paths[['mobile','path','if_order']]

In [25]:
df_paths.head()

        mobile                                               path  if_order
0  13000000003  008002007000_tp,009002002000_tp,002011005003_t...         0
1  13000000004                    002011002000_tp,002011002000_tp         0
2  13000000005  008002007000_tp,009002004000_tp,002011005003_t...         0
3  13000000008    002011005007_tp,002011005007_tp,002011004000_tp         0
4  13000000012                                    002011005007_tp         0

## 战败激活归因

In [26]:
data = {
    "path": df_paths.path.values.tolist(),
    "conversions": df_paths.if_order.values.tolist()
}

data = pd.DataFrame(data)

df = pd.DataFrame(data)

path_feature="path"
conversion_feature="conversions"
null_feature=None

separator=","
k_order=1
n_simulations=10000
max_steps=None
return_transition_probs=True
random_state=26

# instantiate the model
mm = MarkovModel(path_feature=path_feature,
                 conversion_feature=conversion_feature,
                 null_feature=null_feature,
                 separator=separator,
                 k_order=k_order,
                 n_simulations=n_simulations,
                 max_steps=max_steps,
                 return_transition_probs=return_transition_probs,
                 random_state=random_state)

# fit the model
mm.fit(df)

/app/anaconda3/envs/python37_smcsandbox/lib/python3.7/site-packages/pychattr/channel_attribution/_markov.py:91: RuntimeWarning: divide by zero encountered in double_scalars
  num_transitions[k] /= vsm[w]

In [27]:
remove_effects = mm.removal_effects_.merge(id_mapping[['touchpoint_id','touchpoint_name']],left_on = 'channel_name',right_on = 'touchpoint_id').sort_values(by = 'removal_effect',ascending = False)[['touchpoint_id','touchpoint_name','removal_effect']]
## get share in results
remove_effects['share_in_result'] = remove_effects['removal_effect'] / remove_effects.removal_effect.sum()

In [28]:
remove_effects.head(50)

      touchpoint_id      touchpoint_name  removal_effect  share_in_result
16  009002001000_tp             销售代表跟进邀约          0.5413         0.082889
10  009002004000_tp           销售代表跟进进入展厅          0.4541         0.069536
1   009002002000_tp             销售代表跟进电话          0.4420         0.067683
17  009002003000_tp           销售代表跟进展厅接待          0.4328         0.066275
20  009002007000_tp             销售代表跟进其他          0.3929         0.060165
15  001001002000_tp              线索首触-地域          0.3479         0.053274
14  001001001000_tp              线索首触-品牌          0.3128         0.047899
18  001008001001_tp               汽车之家采买          0.2930         0.044867
31  006000000000_tp                 线下到店          0.2508         0.038405
4   014003000000_tp               同意战败申请          0.2480         0.037976
53  007004000000_tp               评价试乘试驾          0.2319         0.035511
38  001008003001_tp                易车网采买          0.2240         0.034301
60  001008002001_tp                懂车帝采买          0.1827         0.027977
51  002001002000_tp                APP注册          0.1745         0.026721
29  007001004000_tp           其他渠道预约试乘试驾          0.1341         0.020535
30  007002002000_tp               预约试驾确认          0.1284         0.019662
58  007003000000_tp               完成试乘试驾          0.1206         0.018467
48  003001004000_tp               展厅首页点击          0.1066         0.016324
3   014004000000_tp                 完全战败          0.1024         0.015681
45  015000000000_tp                 战败唤醒          0.0921         0.014103
46  002009001003_tp               签到获取积分          0.0920         0.014088
24  008001004000_tp                展厅活动类          0.0809         0.012388
36  008001001000_tp                团购促销类          0.0649         0.009938
57  008001009002_tp                   车展          0.0576         0.008820
34  009003004000_tp             DLM呼出未接通          0.0555         0.008499
49  002009001001_tp                 获取积分          0.0515         0.007886
66  003001008000_tp              配置详情页点击          0.0497         0.007611
6   002011005007_tp             收到短信其他主题          0.0476         0.007289
83  002002002001_tp         社区文章浏览[0,5)s          0.0460         0.007044
62  002009002006_tp                 商城下单          0.0392         0.006003
47  002009001004_tp           完善个人资料获取积分          0.0329         0.005038
54  009003003004_tp       DLM呼出接通时长>=60s          0.0312         0.004778
63  003001010000_tp           整车商城订购首页点击          0.0301         0.004609
7   002011002000_tp             SIS外呼未接通          0.0286         0.004380
86  002010001000_tp         APP金融产品介绍页点击          0.0269         0.004119
50  003001007000_tp               试驾首页点击          0.0259         0.003966
39  008002001000_tp                 活动直播          0.0242         0.003706
11  002011004000_tp              AI外呼未接通          0.0195         0.002986
43  001009001001_tp              SIS战败客户          0.0192         0.002940
40  008001007001_tp                低成本集客          0.0189         0.002894
92  012001000000_tp                 保客活动          0.0187         0.002864
91  002002002002_tp        社区文章浏览[5,30)s          0.0186         0.002848
90  009003003003_tp  DLM呼出接通时长[30s, 60s)          0.0182         0.002787
67  003001011000_tp            整车商城支付页点击          0.0177         0.002710
41  002001003003_tp              ZEBRA注册          0.0175         0.002680
75  009002005000_tp             销售代表跟进短信          0.0153         0.002343
42  002011001004_tp         SIS接通时长>=60s          0.0138         0.002113
82  008001008000_tp                  试驾会          0.0137         0.002098
32  008001002000_tp                  外展类          0.0135         0.002067
68  003001005001_tp              点击全新MG5          0.0130         0.001991

In [29]:
remove_effects.to_csv('全量下定贡献度_final.csv',index = False)